### ISSUE TITLE
3.0.15 - DHCP relaying - giaddr is not modified in relayed packet

### ISSUE THREAD

**Issue by nchaigne** [FreeRADIUS/freeradius-server#2092]
# Issue type
- [x] Defect - Unexpected behaviour (obvious or verified by project member).

# Defect/Feature description
## How to reproduce issue

I'm using FreeRADIUS (3.0.15) virtual server dhcp.relay to forward DHCP packets (Discover / Request) to a DHCP Server.
Expected: FreeRADIUS updates the "giaddr" DHCP field in the relayed packet.
Observed: the giaddr in the relayed packet is not modified (confirmed by a network capture). Consequently, the DHCP server does not send the response to FreeRADIUS, but to the previous DHCP relay instead.

 
## Output of ``[radiusd|freeradius] -X`` showing issue occurring

This does not show the issue, but this is what the server outputs when it happens.

```text
Thu Oct 12 16:08:18 2017 : Debug: (1) Received code 1025 Id 1 from 10.11.19.3:67 to 10.11.19.12:67 length 300
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Opcode = Client-Message
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Hardware-Type = Ethernet
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Hardware-Address-Length = 6
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Hop-Count = 1
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Transaction-Id = 1
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Number-of-Seconds = 0
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Flags = 0
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Client-IP-Address = 0.0.0.0
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Your-IP-Address = 0.0.0.0
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Server-IP-Address = 0.0.0.0
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Gateway-IP-Address = 10.11.19.3
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Client-Hardware-Address = 44:48:42:00:01:01
Thu Oct 12 16:08:18 2017 : Debug: (1)   DHCP-Message-Type = DHCP-Discover
Thu Oct 12 16:08:18 2017 : Debug: Trying sub-section dhcp DHCP-Discover {...}
Thu Oct 12 16:08:18 2017 : Debug: (1)   dhcp DHCP-Discover {
Thu Oct 12 16:08:18 2017 : Debug: (1)     update config {
Thu Oct 12 16:08:18 2017 : Debug: (1)       &DHCP-Relay-To-IP-Address := 10.11.19.28
Thu Oct 12 16:08:18 2017 : Debug: (1)     } # update config = noop
Thu Oct 12 16:08:18 2017 : Debug: (1)     update request {
Thu Oct 12 16:08:18 2017 : Debug: (1)       &DHCP-Gateway-IP-Address := 10.11.19.12
Thu Oct 12 16:08:18 2017 : Debug: (1)       Overwriting value "10.11.19.3" with "10.11.19.12"
Thu Oct 12 16:08:18 2017 : Debug: (1)     } # update request = noop
Thu Oct 12 16:08:18 2017 : Debug: (1)     modsingle[post-auth]: calling ok (rlm_always)
Thu Oct 12 16:08:18 2017 : Debug: (1)     modsingle[post-auth]: returned from ok (rlm_always)
Thu Oct 12 16:08:18 2017 : Debug: (1)     [ok] = ok
Thu Oct 12 16:08:18 2017 : Debug: (1)   } # dhcp DHCP-Discover = ok
Sending DHCP-Discover Id 00000001 from 10.11.19.12:67 to 10.11.19.28:67
Thu Oct 12 16:08:18 2017 : Debug: (1) Not sending reply to client.
Thu Oct 12 16:08:18 2017 : Debug: (1) Finished request
Thu Oct 12 16:08:18 2017 : Debug: (1) Cleaning up request packet ID 1 with timestamp +24
Thu Oct 12 16:08:18 2017 : Info: Ready to process requests
```

**Comment by nchaigne** [comment]
Function "dhcprelay_process_client_request" (dhcpd.c) calls "fr_dhcp_encode" (dhcp.c).

But fr_dhcp_encode does nothing if packet->data is defined, which is the case because we're working on the packet received.

I think that's the issue.

**Comment by alandekok** [comment]
Ah, yes, that's it.  I'll see if I can have a patch later today.

**Comment by nchaigne** [comment]
I think there's more to this. Reading "dhcprelay_process_server_reply", I don't know how this could work...

First we assign "dst_ipaddr" to "giaddr". This is wrong, because we've changed giaddr before relaying. (but this does nothing because of the second point below).

Second, we "unicast to ciaddr if present otherwise to yiaddr". This won't work if we've received from a relay, in this case we want to unicast to the previous relay's giaddr (which we no longer know as we've overwriten the packet before relaying...).

How about the following:
- If we've received a packet with "giaddr" (i.e. from a relay), then we must unicast the response to this giaddr.
- If not, then do as now.
=> this would require to store the initial packet giaddr.

**Comment by nchaigne** [comment]
Apparently this attribute already exists (DHCP-Relay-IP-Address).

But in dhcp_process we have:
return dhcprelay_process_server_reply(request);

So the part of dhcp_process which makes use of DHCP-Relay-IP-Address is never executed...

**Comment by alandekok** [comment]
The `dhcprelay_process_server_reply()` function is called only for reply packets, so it won't affect request packets.  i.e. don't look at `dhcprelay_process_server_reply()`, because it's for DHCP offer or DHCP ACK packets.  Which doesn't apply here.

The next line checks for `DHCP-Relay-IP-Address`, and calls `dhcprelay_process_client_request()` if the attribute exists.  So it *should* be relaying the packet in that function.

The issue really seems to be that `dhcp_encode()` does nothing if `request->packet->data != NULL`.  The solution is small fix in `dhcprelay_process_client_request()`.

From the looks of it, `dhcprelay_process_server_reply()` also needs fixing

**Comment by nchaigne** [comment]
I've fixed dhcprelay_process_client_request with a "TALLOC_FREE(request->packet->data);" before calling fr_dhcp_encode.

Now, I'm looking at dhcprelay_process_server_reply because I'm trying to handle Offer / Ack, and it doesn't work...

That's why I'm trying to figure out how DHCP-Relay-IP-Address works. But it seems that we don't have this attribute when we're receiving an Offer / Ack, because it's not correlated with the initial Discover / Offer ?

If this is the case, I don't know how to send the response to the correct IP address...

**Comment by alandekok** [comment]
> If this is the case, I don't know how to send the response to the correct IP address...

Responses *should* be sent to giaddr from the packet.  If the giaddr is the current system, then the response should be unicast if yiaddr exists, otherwise it's broadcast.

All of that logic is in `dhcprelay_process_server_reply()`.  Which incidentally is also wrong... it updates `request->packet` in some places, and `request->reply` in others.

I'll push a fix.

**Comment by alandekok** [comment]
I haven't tested the fix, but it should work.  Plus, it should fix the issues with `dhcprelay_process_server_reply()`

**Comment by nchaigne** [comment]
"Responses should be sent to giaddr from the packet".

I don't think that's correct. The "packet" is an Offer, so "giaddr" is ourselves (because we've modified that when relaying).

And we need to relay back the Offer to the previous giaddr (if there was one, i.e. FreeRADIUS is a relay after another relay), which we don't know anymore.

**Comment by nchaigne** [comment]
Thanks for the fix, I'll test that.

**Comment by nchaigne** [comment]
There are two issues:

1) when handling the response, "packet" do not have any vps so the DHCP packet encoded is full of zeroes. (this one was easy to fix, you forgot the "hackity hack" before calling fr_dhcp_encode, in dhcprelay_process_server_reply)

2) but the reply is broadcast. The server does not know that it originally received the request from another relay, to which it should unicast the response.

**Comment by alandekok** [comment]
If we don't have another giaddr, then we can't relay the packet to it.  I've pushed another fix to make that clearer.

What COULD happen is to add some checks for (say) `giaddr` in the `request->config` list.  If that's set, then send the packet there, instead of to `ciaddr` or `yiaddr`.  You would still have to track and set `giaddr` manually somehow, but it would work.

All this will be fixed in 4.0. :(  The DHCP relay functionality will be a separate module that just does the right thing...

**Comment by nchaigne** [comment]
Another minor issue with the port:

3. In dhcprelay_process_server_reply:
	packet->dst_port = packet->dst_port;		/* server port */

This should be:
	packet->dst_port = request->packet->dst_port;

**Comment by nchaigne** [comment]
I can't store giaddr in request->config. :'(
When FreeRADIUS handles the response, we do not have "request->config" from the initial request.

Oh well... I suppose it would be too much work to fix this in 3.0.x.

I'm sure I'm not the first to ask this, but... any idea (very roughly) when 4.0 could be usable ?

**Comment by nchaigne** [comment]
Alright I have a (dirty) solution.

In dhcprelay_process_server_reply I've added:

```text
	// unicast the response to the previous relay (if there was one)
	vp = fr_pair_find_by_num(request->config, 270, DHCP_MAGIC_VENDOR, TAG_ANY); /* DHCP-Relay-To-IP-Address */
	// should use another (new) attribute ? DHCP-Relay-From-IP-Address maybe ?
	if (vp) {
		RDEBUG("DHCP: response will be relayed to previous gateway");
		packet->dst_ipaddr.ipaddr.ip4addr.s_addr = vp->vp_ipaddr;
	} else
```

And in my virtual server I have:

```text
	dhcp DHCP-Offer {
		update config {
			&DHCP-Relay-To-IP-Address := 10.11.19.3
		}
	}
```


That's ugly.
To make it work I have to run X virtual servers, one for each relay.
But it works...

FreeRADIUS 4.0, just so you know... you're eagerly expected. :)

**Comment by alandekok** [comment]
That works.  I'll push a fix.

You should be able to use one virtual server, and update the relay IP address via a database lookup.

**Comment by alandekok** [comment]
The one caveat with the fix is that `giaddr` is left alone, and is the IP of the FreeRADIUS gateway.  That should be fixed.

**Comment by nchaigne** [comment]
You're right about giaddr, forgot about that. If the previous relay was also a FreeRADIUS it would not have worked.

Thanks for the multiple fixes :)

**Comment by alandekok** [comment]
Please verify this all works, and I'll close the issue, you you can close it if it's verified.

**Comment by nchaigne** [comment]
Everything works, this can be closed.
