### ISSUE TITLE
failover not working with home_servers on TLS

### ISSUE THREAD

**Issue by pauldekkers** [FreeRADIUS/freeradius-server#2284]
# Issue type

- Defect - Unexpected behaviour

When I have a proxy configuration for two home_servers in a pool with type = fail-over, the second server doesn't get requests for a fail-over situation.

I'm basically using the config from the sites-available/tls

With FreeRADIUS stable 3.0.17 release or 3.0.x from this morning
using EAPTest as test client (for simple PAP requests, so just out of convenience)

(I think I did see a failover occur in the past when there were small glitches to a server, but apparently not when it's completely unreachable? I have no proof of that.)

# Defect
## How to reproduce the issue

Ubuntu 18.04.1 LTS, FreeRADIUS 3.0.17 or 3.0.x from this morning, compiled with only a different prefix but libssl-dev and other dependencies present

First home_server is unreachable, second is never tried (regardless of it being reachable).

Errors displayed are:

Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (192.168.0.3, 2083)' : Failed connecting socket: Connection refused
(208) Failed to insert request into the proxy list

Suppressing attempt to open socket to 'down' home server
(209) Failed to insert request into the proxy list

Expected behavior is that after a timeout the second server is tried. Yet, tcpdump never shows connection attempts.

Default configuration, except a client in client.conf, and this proxy.conf:

```
home_server ONE {
        ipv4addr = 192.168.0.3
        port = 2083
        type = auth+acct
        secret = radsec
        status_check = none
        proto = tcp
        tls {
                private_key_file = /opt/localhost.pem
                certificate_file = /opt/localhost.pem
                dh_file = ${certdir}/dh
                random_file = /dev/urandom
                fragment_size = 8192
                ca_file = /opt/localhost.pem
                cipher_list = "DEFAULT"
        }
        #response_window = 4
        #response_timeouts = 30
        #zombie_period = 120
        #status_check = none
        #revive_interval = 60
}

home_server TWO {
        ipaddr = 192.168.0.249
        port = 2083
        type = auth+acct
        secret = radsec
        proto = tcp
        tls {
                private_key_file = /opt/localhost.pem
                certificate_file = /opt/localhost.pem
                dh_file = ${certdir}/dh
                random_file = /dev/urandom
                fragment_size = 8192
                ca_file = /opt/localhost.pem
                cipher_list = "DEFAULT"
        }
        #response_window = 4
        #response_timeouts = 30
        #zombie_period = 120
        #status_check = none
        #revive_interval = 60
}

home_server ONE_UDP {
        type = auth+acct
        ipaddr = 192.168.0.3
        port = 1812
        secret = testing123
}

home_server TWO_UDP {
        type = auth+acct
        ipaddr = 192.168.0.249
        port = 1812
        secret = testing123
}

home_server_pool POOL {
        type = fail-over
        home_server = ONE
        home_server = TWO
}

realm DEFAULT {
        pool = POOL
        nostrip
}
```

If I use home_servers ONE_UDP and TWO_UDP, failover does happen. Or if the first is UDP and second TCP.

Enabling the commented parameters for failover (or changing them a bit) doesn't help.

I can simulate with iptables by inserting a -j DROP to the target or -j REJECT, with DROP things get worse.

## Output of ``[radiusd|freeradius] -X`` showing issue occurring

Most likely errors are (without attempting a second server):

```
Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (192.168.0.3, 2083)' : Failed connecting socket: Connection refused
(208) Failed to insert request into the proxy list

Suppressing attempt to open socket to 'down' home server
(209) Failed to insert request into the proxy list
```

This is when the request is really dropped, by a -j DROP (on the remote host for instance):

```
(0) Starting proxy to home server 192.168.0.3 port 2083
Waking up in 0.3 seconds.
Waking up in 0.4 seconds.
Waking up in 0.7 seconds.
Waking up in 1.1 seconds.
Waking up in 1.6 seconds.
(0) Ignoring duplicate packet from client world port 55884 - ID: 90 due to unfinished request in component <core> module
Waking up in 0.3 seconds.
Waking up in 2.5 seconds.
Waking up in 3.7 seconds.
(0) Ignoring duplicate packet from client world port 55884 - ID: 90 due to unfinished request in component <core> module
Waking up in 2.6 seconds.
Waking up in 5.6 seconds.
(0) Ignoring duplicate packet from client world port 55884 - ID: 90 due to unfinished request in component <core> module
Waking up in 4.3 seconds.
Waking up in 8.5 seconds.
Waking up in 12.8 seconds.
Unresponsive child for request 0, in component <core> module
Waking up in 19.2 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Waking up in 9.9 seconds.
Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (192.168.0.3, 2083)' : Failed connecting socket: Connection timed out
(0) Failed to insert request into the proxy list
Thread 5 waiting to be assigned a request
(0) Cleaning up request packet ID 90 with timestamp +5
Ready to process requests
```

Never attempts to use the second host.

Interestingly, if I use a failover from a UDP home_server to TCP, that works:

```
home_server_pool POOL {
        type = fail-over
        home_server = ONE_UDP
        home_server = TWO
}
```

```
Thread 3 waiting to be assigned a request
(2) Expecting proxy response no later than 29.668010 seconds from now
Waking up in 2.9 seconds.
(0) No proxy response, giving up on request and marking it done
Marking home server 192.168.0.3 port 1812 as zombie (it has not responded in 30.000000 seconds).
(0) ERROR: Failing proxied request for user "test1", due to lack of any response from home server 192.168.0.3 port 1812
Waking up in 0.3 seconds.
Thread 2 got semaphore
Thread 2 handling request 0, (1 handled so far)
...
PING: Zombie period is over for home server ONE_UDP
Marking home server 192.168.0.3 port 1812 as dead.
PING: Reviving home server ONE_UDP in 300 seconds
...
(3) Starting proxy to home server 192.168.0.249 port 2083
```

**Comment by alandekok** [comment]
For UDP home servers, FreeRADIUS uses one source port, and leaves it open.

The issue is that for TCP (or TLS) home servers, FreeRADIUS tries to open a new connection / socket.  If that fails, it doesn't mark the home server as "zombie".  Instead, it just fails.

I'll take a look.

**Comment by alandekok** [comment]
I've pushed a fix which should help.  Please verify before we release 3.0.18

**Comment by pauldekkers** [comment]
If a TCP-connection can't be established, FreeRADIUS will still never try again.
```
(0) Starting proxy to home server 127.0.0.1 port 2084
Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (127.0.0.1, 2084)' : Failed connecting socket: Connection refused
(0) Failed to insert request into the proxy list

...

(1) Starting proxy to home server 127.0.0.1 port 2085
Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (127.0.0.1, 2085)' : Failed connecting socket: Connection refused
(1) Failed to insert request into the proxy list

...

(2) ERROR: Failed to find live home server: Cancelling proxy
(2) WARNING: No home server selected
```
(and it never restores)

Failover worked fine to a secondary server if the connection to the primary was interrupted, and it even restored after a while to the primary (only if it was reachable - if it's not: same as above).

Also FreeRADIUS doesn't retry a transmission to the second home_server if a request fails, but the client will retransmit - so I guess that will work. (And I think it's the same for UDP connections anyway.)

**Comment by alandekok** [comment]
Are those comments with or without the patch I just pushed?

**Comment by pauldekkers** [comment]
Last two comments were all with your latest patch; it sure did something, there is failover now but failed servers that fail in their connection attempt are never retried.

**Comment by pauldekkers** [comment]
That patch after your comment from commit https://github.com/FreeRADIUS/freeradius-server/commit/7631c29fc90e4fc6c3e79972a1e48f372f70f5c9 I didn’t try yet; will do that later!

**Comment by pauldekkers** [comment]
With https://github.com/FreeRADIUS/freeradius-server/commit/7631c29fc90e4fc6c3e79972a1e48f372f70f5c9 I still don't see the server being marked as dead when it's just not reachable right after starting;

```
(0) Starting proxy to home server 127.0.0.1 port 2084
Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (127.0.0.1, 2084)' : Failed connecting socket: Connection refused
Waking up in 0.3 seconds.
(0) Failed to insert request into the proxy list
```

And it's never resumed.

**Comment by pauldekkers** [comment]
What now does work (after https://github.com/FreeRADIUS/freeradius-server/commit/162aa91f71c4657d3944b80621af568d76fea8aa) is:
- Connecting to a fail-over server for subsequent request, if the first server fails

Always worked:
- Reconnecting to the same server after a home_server got disconnected (eg. restarting remote process)

Still not working:
- Server never retried after "Failed opening new proxy socket 'proxy (0.0.0.0, 0) -> home_server (IP, port)' : Failed connecting socket: _some error_", and at some point all servers in a pool are tried once and never again
- If traffic is dropped to the destination for an established connection, one has to wait for the TCP session to timeout (which can take 2 hours with default settings); there is no other keepalive check in FreeRADIUS - this could happen with routing issues or crashing servers easily, and one would expect to failover

I actually don't see what https://github.com/FreeRADIUS/freeradius-server/commit/7631c29fc90e4fc6c3e79972a1e48f372f70f5c9 improved

**Comment by alandekok** [comment]
You should be able to set `idle_timeout` on the TCP socket so that it's closed if it's unused.

The patch in 7631c29 should have made it mark the home server `dead` when the request was cleaned up.  Unless it had failed over to another home server in the mean time...

I don't think this fix will be trivial.  The simplest approach TBH would be to just set timers for all TCP home servers to check their status, reconnect, etc.

**Comment by pauldekkers** [comment]
Sorry, I just tried going back to before 162aa91f71c4657d3944b80621af568d76fea8aa; I noticed that while failover to a second server didn't work without the patch, the first server is tried again time after time. So it's really the first patch that fixes the fail-over, but breaks a home_server in that it never goes back to a working state after a connection failure.

Hope this helps.

**Comment by alandekok** [comment]
The earlier code always retried the first home server, because the home server was always marked alive.

Marking it "dead" when the connection fails means that fail-over now works.  But the first home server still has to be marked "alive" again.

I'll see if there's a better way to fix it.

**Comment by alandekok** [comment]
The last commit should fix it all.

**Comment by pauldekkers** [comment]
Thanks! This patch works well, I tried it with various scenarios (fail-over, load-balancing, traffic drops, resets), stressing it and some production hours. Two remarks:

If there is just one home_server, I think a minimum revive_interval of 60 is a bit long; I'd rather have that as an unconfined value (before the patches it was way shorter). Most peers have multiple servers of course (but some do load-balancing or fail-over in hardware appliances and may have one). But even then, both can be restarted one after the other after a configuration change. I don't see a problem in setting it (much) lower?

Second; There is one scenario in which I can block the entire server, not making it receive UDP traffic either. I'm not sure how hypothetical this is, take this experiment with a grain of salt. But it's easy to reproduce.

If the traffic is dropped to a home_server while the connection was open, and there are still a lot of requests for that realm coming in (tested >20auths/s), I see FUTEX_WAIT_ calls. I guess all threads block. Some strace outputs while capturing the effect, while I dropped traffic with ip(6)tables:

```
strace: Process 17117 attached with 6 threads
[pid 17123] futex(0x562a1d243170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
[pid 17122] futex(0x562a1d243170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
[pid 17121] futex(0x562a1d243170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
[pid 17120] futex(0x562a1d243170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
[pid 17119] futex(0x562a1d243170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff <unfinished ...>
[pid 17117] connect(15, {sa_family=AF_INET6, sin6_port=htons(2083), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28
```

It's not always the same call:

```
[pid 17483] write(1, "\33[1m ... shutting down socket pr"..., 90) = 90
[pid 17483] futex(0x564a2d472280, FUTEX_WAIT_PRIVATE, 2, NULL

 <unfinished ...>
[pid 17487] <... connect resumed> )     = -1 ETIMEDOUT (Connection timed out)
[pid 17487] futex(0x7f6514167e2c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
```

```
[pid 17487] futex(0x564a2d472170, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, 0xffffffff

 <unfinished ...>
[pid 17486] <... connect resumed> )     = -1 ETIMEDOUT (Connection timed out)
[pid 17486] close(15)                   = 0
[pid 17486] write(1, "\33[31mFailed opening new proxy so"..., 133) = 133
```

Again, not sure how hypothetical this is, and the revive_interval bothers me more ;-)

**Comment by alandekok** [comment]
I've lowered the minimum `revive_interval`.

The problem with `futex_wait` is likely some OS issue.  i.e. dropping the TCP connection without any feedback is just about the worst thing you can do to it.  The OS has no way of knowing that the connection is gone.  And therefore has no way of telling the application that the connection is gone.

We're fixing this in v4 by making the IO asynchronous.  Which means that instead of blocking, we can notice that the socket hasn't been ready / used for a long time.  And then can be closed.

**Comment by pauldekkers** [comment]
Happy with the new `revive_interval`!

The `futex_wait` issue it not a big deal I think, this must be a rare condition and it’s good to hear how version 4 will deal with this.

Thanks for the fixes!
